name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * *" # roda diariamente à meia-noite UTC
  workflow_dispatch:     # permite executar manualmente

jobs:
  update-readme:
    name: Update waka stats
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_API_KEY }}
